
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggfgfkvihtrxntjgeboi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnZmdma3ZpaHRyeG50amdlYm9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTk5NDAsImV4cCI6MjA1OTk3NTk0MH0.XtJ9_KniBKCHJtSC-2owq-8ZTecW56jx36LmS7DwjMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add type augmentation for Supabase tables
declare module '@supabase/supabase-js' {
  interface Database {
    public: {
      Tables: {
        statuts: {
          Row: {
            id: string;
            code: string;
            libelle: string;
            couleur: string;
            display_order?: number;
            created_at?: string;
            updated_at?: string;
          }
        };
        employes: {
          Row: {
            id: string;
            nom: string;
            prenom?: string | null;
            departement?: string | null;
            fonction?: string | null;
            role?: string | null;
            uid?: string | null;
            created_at?: string | null;
            updated_at?: string | null;
          }
        };
        employe_schedule: {
          Row: {
            id: string;
            employe_id?: string | null;
            date: string;
            period: string;
            statut_code: string;
            project_code?: string | null;
            is_highlighted?: boolean | null;
            note?: string | null;
            created_at?: string | null;
          }
        };
        taches: {
          Row: {
            id: number;
            created_at?: string | null;
          }
        };
        connection_logs: {
          Row: {
            id: string;
            event_type?: string | null;
            user_id?: string | null;
            user_name?: string | null;
            ip_address?: string | null;
            user_agent?: string | null;
            created_at?: string | null;
          }
        };
        projets: {
          Row: {
            id: string;
            code: string;
            name: string;
            color: string;
            created_at?: string | null;
            updated_at?: string | null;
          }
        };
      };
    };
  }
}
