// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggfgfkvihtrxntjgeboi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnZmdma3ZpaHRyeG50amdlYm9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTk5NDAsImV4cCI6MjA1OTk3NTk0MH0.XtJ9_KniBKCHJtSC-2owq-8ZTecW56jx36LmS7DwjMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);